# Generated by Django 3.2.8 on 2021-11-15 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_level',
            new_name='class_level_id',
        ),
    ]
