# Generated by Django 3.2.8 on 2021-11-15 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelpages', '0003_alter_student_class_level_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_level_id',
            new_name='class_level',
        ),
    ]
