# Generated by Django 3.2.8 on 2021-11-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelpages', '0005_alter_student_class_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_level',
        ),
        migrations.AddField(
            model_name='student',
            name='class_level_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='travelpages.grade_level', verbose_name='student class'),
        ),
    ]
