# Generated by Django 3.2.8 on 2021-11-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelpages', '0006_auto_20211117_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_level_id',
            new_name='class_level',
        ),
    ]
