# Generated by Django 3.2.8 on 2021-11-23 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoviesApp.category')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=1000)),
                ('movie_id', models.ManyToManyField(through='MoviesApp.Movie', to='MoviesApp.Category')),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoviesApp.rating'),
        ),
    ]
